# syntax=docker/dockerfile:1
FROM python:3.8.10

WORKDIR /usr/src/app

COPY requirements.txt ./
RUN /usr/local/bin/python -m pip install --upgrade pip
RUN pip install --no-cache-dir -r requirements_docker.txt

COPY ./join .
CMD gunicorn join.wsgi.py:application --bind 0.0.0.0:$PORT