# Generated by Django 4.0.3 on 2022-03-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=2000)),
                ('category', models.CharField(max_length=100)),
                ('due_date', models.DateTimeField(verbose_name='dead line')),
                ('created_at', models.DateTimeField(verbose_name='created at')),
            ],
        ),
    ]
